# Generated by Django 2.2.2 on 2019-06-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0002_auto_20190612_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='inn',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='position',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
