# Generated by Django 2.2.2 on 2019-06-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0004_auto_20190618_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'IT'), (1, 'finance'), (2, 'staff'), (3, 'marketing'), (4, 'retail'), (5, 'other')], db_index=True, default=5),
        ),
    ]
